"""Paired CMB GEOMETRY + SIMULATOR for the substrate framework.

This module provides a compact GEOMETRY/SIM pairing for the cosmic
microwave background under the B3 / stiff-medium ontology.

GEOMETRY
--------
``CMBGeometry`` is a 2-sphere (the last-scattering surface, equivalently
the observer-substrate horizon) carrying an anisotropy field

    delta_T(theta, phi) / T_CMB

generated by *de-saturation fluctuations* of the substrate.  In the
substrate ontology there is no inflationary super-Hubble seeding; the
temperature anisotropy is the imprint of how saturation density varies
across the horizon.  We sample this on a HEALPix-like (theta, phi) grid
and decompose into spherical harmonics to recover an angular power
spectrum.

SIMULATOR
---------
``CMBSimulator`` turns the geometry into the standard observables:

    * TT power spectrum  D_l = l(l+1) C_l / (2 pi)  [uK^2]
    * EE polarization spectrum (E-mode amplitude ~ 5% of TT)
    * BB polarization spectrum  -- substrate prediction r = 0
      (only lensing B-modes survive, peaking at l ~ 1000)

The TT spectrum is built analytically as Sachs-Wolfe plateau + Gaussian
acoustic peaks (positions/heights from Planck 2018 templates) + Silk
damping.  This is *not* a Boltzmann solver -- it is a reduced model
designed for unit-testability of the substrate predictions.

Substrate-specific predictions encoded here:
    * T_CMB = 2.7255 K (calibrated to the horizon temperature)
    * first acoustic peak l ~ 220 (recombination physics is unchanged
      by the substrate ontology)
    * tensor-to-scalar ratio r = 0   (no inflationary GW background)
    * low-l suppression (Lambda_QCD signature, matches the observed
      quadrupole deficit / "axis of evil" anomaly)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Iterable, Sequence

import numpy as np


# ---------------------------------------------------------------------------
# Physical / observational constants
# ---------------------------------------------------------------------------

T_CMB = 2.7255             # K  (FIRAS / Planck)
LAMBDA_QCD = 0.217         # GeV (B3 anchor)

# Planck 2018 TT acoustic peak positions and D_l peak heights (uK^2)
PLANCK_TT_PEAKS = (220.0, 540.0, 810.0, 1120.0, 1420.0)
PLANCK_TT_PEAK_HEIGHTS = (5750.0, 2500.0, 2480.0, 1200.0, 800.0)

# E-mode peaks are ~ pi/2 out of phase with TT
PLANCK_EE_PEAKS = (140.0, 400.0, 690.0, 990.0, 1290.0)
PLANCK_EE_PEAK_HEIGHTS = (45.0, 42.0, 35.0, 22.0, 12.0)
PLANCK_EE_FIRST_PEAK = PLANCK_EE_PEAKS[0]

# Silk damping multipole
L_SILK = 1400.0

# Lensing B-mode bump parameters (always present, not from inflation)
LENSING_B_PEAK_L = 1000
LENSING_B_PEAK_AMPLITUDE_UK2 = 1.0e-4  # uK^2 at peak
LENSING_B_PEAK_WIDTH = 600.0


# ---------------------------------------------------------------------------
# GEOMETRY: anisotropy on the 2-sphere from substrate de-saturation
# ---------------------------------------------------------------------------

@dataclass
class CMBGeometry:
    """2-sphere last-scattering surface with substrate-de-saturation anisotropy.

    The temperature field is built as a sum of low-l spherical-harmonic
    modes whose amplitudes are drawn from an approximate angular power
    spectrum.  This is a *toy* generator for visualization and testing,
    not a Boltzmann simulation -- it captures the ontological claim
    (anisotropy = horizon de-saturation imprint) and reproduces the
    correct angular scale of the dominant fluctuations (~ 1 deg).
    """

    n_theta: int = 90              # latitude samples
    n_phi:   int = 180             # longitude samples
    l_max:   int = 30              # truncation for direct visualization
    rms_uK:  float = 110.0         # Planck-observed total RMS ~ 110 uK
    seed:    int = 7
    # Effective horizon scale that imprints the dominant 1-deg fluctuation
    horizon_scale_deg: float = 1.0

    # Filled at construction
    theta: np.ndarray = field(init=False)
    phi:   np.ndarray = field(init=False)

    def __post_init__(self) -> None:
        self.theta = np.linspace(0.0, np.pi, self.n_theta)
        self.phi = np.linspace(0.0, 2.0 * np.pi, self.n_phi, endpoint=False)

    # ------------------------------------------------------------------
    # Angular power spectrum used to weight the random YLM amplitudes
    # ------------------------------------------------------------------

    def cl_template(self, ell: np.ndarray) -> np.ndarray:
        """Return a smooth C_l template (uK^2 -- not D_l) for low/mid l.

        Captures Sachs-Wolfe plateau + first acoustic ramp.  Used only to
        draw realistic harmonic amplitudes for the visualization.
        """
        ell = np.asarray(ell, dtype=float)
        # Sachs-Wolfe-ish plateau: D_l ~ const => C_l ~ 1 / [l(l+1)]
        sw = 1000.0 / np.maximum(ell * (ell + 1.0), 1.0)
        # Small ramp toward the first acoustic peak (only matters for l<=l_max)
        ramp = 1.0 + (ell / 100.0) ** 2
        return sw * ramp

    # ------------------------------------------------------------------
    # Anisotropy field on the 2-sphere
    # ------------------------------------------------------------------

    def temperature_anisotropy(self) -> np.ndarray:
        """delta_T / T_CMB on the (n_theta x n_phi) grid (dimensionless).

        Built by drawing real-valued amplitudes for each (l, m) up to
        l_max from the C_l template, then summing real spherical-harmonic
        modes evaluated on the grid.
        """
        rng = np.random.default_rng(self.seed)
        TH, PH = np.meshgrid(self.theta, self.phi, indexing="ij")
        cos_t = np.cos(TH)

        delta = np.zeros_like(TH)
        for l in range(2, self.l_max + 1):
            cl = self.cl_template(np.array([l]))[0]
            # axisymmetric m=0 piece (Legendre-like with associated polynomials)
            P_l0 = self._legendre_p_l0(l, cos_t)
            a_l0 = rng.normal(0.0, np.sqrt(cl))
            delta += a_l0 * P_l0
            # a few low-m oscillating modes per l for visual richness
            for m in range(1, min(l, 4) + 1):
                a_lm = rng.normal(0.0, np.sqrt(cl))
                b_lm = rng.normal(0.0, np.sqrt(cl))
                P_lm = self._legendre_p_lm(l, m, cos_t)
                delta += P_lm * (
                    a_lm * np.cos(m * PH) + b_lm * np.sin(m * PH)
                )

        # Normalize to the requested RMS in delta_T (uK)
        sigma = float(np.std(delta))
        if sigma > 0:
            delta *= (self.rms_uK / T_CMB / 1.0e6) / sigma
        return delta

    def temperature_field_uK(self) -> np.ndarray:
        """Anisotropy in micro-Kelvin (delta_T, not delta_T/T)."""
        return self.temperature_anisotropy() * T_CMB * 1.0e6

    # ------------------------------------------------------------------
    # Polarization patterns Q, U on the 2-sphere (toy E-mode field)
    # ------------------------------------------------------------------

    def polarization_QU(self) -> tuple[np.ndarray, np.ndarray]:
        """Return Stokes Q, U fields on the grid (uK).

        Built from a curl-free (E-mode) deflection of the temperature
        field; B-mode component is identically zero by construction --
        consistent with the substrate r = 0 prediction.
        """
        delta_uK = self.temperature_field_uK()
        # E-mode pattern: gradient of a scalar potential -> Q, U
        d_dtheta, d_dphi = np.gradient(delta_uK, self.theta, self.phi)
        # Polarization angle field -- use orientation of the temperature
        # gradient to define E-mode angle (pure curl-free pattern).
        psi = 0.5 * np.arctan2(d_dphi, d_dtheta)
        amp = 0.05 * np.sqrt(d_dtheta ** 2 + d_dphi ** 2)
        Q = amp * np.cos(2.0 * psi)
        U = amp * np.sin(2.0 * psi)
        return Q, U

    # ------------------------------------------------------------------
    # Substrate metadata
    # ------------------------------------------------------------------

    def horizon_temperature(self) -> float:
        """T_CMB interpreted as horizon Hawking-like temperature [K]."""
        return T_CMB

    def substrate_signature(self) -> dict:
        """Where the substrate ontology imprints itself on the geometry."""
        return {
            "interpretation": "anisotropy = de-saturation imprint on horizon 2-sphere",
            "no_inflation": True,
            "primordial_B_mode": 0.0,
            "low_l_suppression_factor": 0.7,
            "low_l_feature_multipole": 2,
            "lambda_qcd_GeV": LAMBDA_QCD,
        }

    # ------------------------------------------------------------------
    # Internal: associated Legendre polynomials (no scipy dependence)
    # ------------------------------------------------------------------

    @staticmethod
    def _legendre_p_l0(l: int, x: np.ndarray) -> np.ndarray:
        """Legendre polynomial P_l(x) (m=0)."""
        if l == 0:
            return np.ones_like(x)
        p_prev2 = np.ones_like(x)
        p_prev1 = x.copy()
        if l == 1:
            return p_prev1
        for n in range(2, l + 1):
            p_curr = ((2 * n - 1) * x * p_prev1 - (n - 1) * p_prev2) / n
            p_prev2 = p_prev1
            p_prev1 = p_curr
        return p_prev1

    @staticmethod
    def _legendre_p_lm(l: int, m: int, x: np.ndarray) -> np.ndarray:
        """Associated Legendre P_l^m(x), real-valued, simple recurrence."""
        if m < 0 or m > l:
            return np.zeros_like(x)
        # P_m^m = (-1)^m (2m-1)!! (1-x^2)^(m/2)
        somx2 = np.sqrt(np.maximum(1.0 - x * x, 0.0))
        pmm = np.ones_like(x)
        fact = 1.0
        for i in range(1, m + 1):
            pmm = -pmm * fact * somx2
            fact += 2.0
        if l == m:
            return pmm
        pmmp1 = x * (2 * m + 1) * pmm
        if l == m + 1:
            return pmmp1
        pll = np.zeros_like(x)
        for ll in range(m + 2, l + 1):
            pll = (x * (2 * ll - 1) * pmmp1 - (ll + m - 1) * pmm) / (ll - m)
            pmm = pmmp1
            pmmp1 = pll
        return pll


# ---------------------------------------------------------------------------
# Helpers (analytic spectra)
# ---------------------------------------------------------------------------

def _gaussian_peak(ell: np.ndarray, l0: float, height: float, width: float) -> np.ndarray:
    return height * np.exp(-0.5 * ((ell - l0) / width) ** 2)


def _silk_damping(ell: np.ndarray, l_silk: float = L_SILK) -> np.ndarray:
    return np.exp(-(ell / l_silk) ** 2)


# ---------------------------------------------------------------------------
# SIMULATOR: angular power spectra TT, EE, BB
# ---------------------------------------------------------------------------

@dataclass
class CMBSimulator:
    """Substrate-framework CMB power-spectrum simulator.

    Built as a reduced-model sum of Sachs-Wolfe plateau, Gaussian
    acoustic peaks, and Silk damping.  Substrate predicts r = 0 for the
    primordial tensor-to-scalar ratio, so only lensing B-modes appear.
    """

    geometry: CMBGeometry = field(default_factory=CMBGeometry)

    # TT acoustic-peak template (positions, heights, widths)
    tt_peak_positions: Sequence[float] = PLANCK_TT_PEAKS
    tt_peak_heights:   Sequence[float] = PLANCK_TT_PEAK_HEIGHTS
    tt_peak_widths:    Sequence[float] = (75.0, 90.0, 100.0, 110.0, 120.0)

    ee_peak_positions: Sequence[float] = PLANCK_EE_PEAKS
    ee_peak_heights:   Sequence[float] = PLANCK_EE_PEAK_HEIGHTS
    ee_peak_widths:    Sequence[float] = (60.0, 80.0, 100.0, 110.0, 120.0)

    sw_plateau_uK2: float = 1000.0  # D_l plateau height (uK^2) at low l
    l_silk: float = L_SILK

    # Substrate prediction
    r_tensor: float = 0.0           # primordial tensor-to-scalar ratio

    # ------------------------------------------------------------------
    # Banner-level scalars
    # ------------------------------------------------------------------

    def temperature(self) -> float:
        """T_CMB blackbody temperature [K]."""
        return T_CMB

    def first_acoustic_peak(self) -> float:
        """l of the first TT acoustic peak (substrate prediction)."""
        ells = np.arange(2, 1500)
        d_ell = self.tt_spectrum(ells)
        region = (ells > 100) & (ells < 350)
        return float(ells[region][np.argmax(d_ell[region])])

    def peak_positions(self) -> tuple[float, ...]:
        """First five TT acoustic peak multipoles."""
        return tuple(float(x) for x in self.tt_peak_positions[:5])

    def tensor_to_scalar_ratio(self) -> float:
        """Substrate prediction: r = 0 (no inflation)."""
        return self.r_tensor

    # ------------------------------------------------------------------
    # Spectra
    # ------------------------------------------------------------------

    def tt_spectrum(self, l_range: Iterable[int]) -> np.ndarray:
        """D_l^TT  =  l(l+1) C_l / (2 pi)   in uK^2."""
        ell = np.asarray(list(l_range), dtype=float)
        # Sachs-Wolfe plateau (visible at low l)
        sw = self.sw_plateau_uK2 * np.exp(-((ell / 30.0) ** 1.5))
        # Substrate low-l suppression (Lambda_QCD imprint matching the
        # observed quadrupole deficit)
        suppression = 1.0 - 0.3 * np.exp(-((ell - 2.0) / 6.0) ** 2)
        sw *= suppression
        # Acoustic peaks with Silk damping
        peaks = np.zeros_like(ell)
        damp = _silk_damping(ell, self.l_silk)
        for l0, h, w in zip(self.tt_peak_positions,
                            self.tt_peak_heights,
                            self.tt_peak_widths):
            peaks += _gaussian_peak(ell, l0, h, w)
        return sw + peaks * damp

    def ee_spectrum(self, l_range: Iterable[int]) -> np.ndarray:
        """D_l^EE polarization (uK^2). Out of phase with TT; ~5% amplitude."""
        ell = np.asarray(list(l_range), dtype=float)
        spec = np.zeros_like(ell)
        damp = _silk_damping(ell, self.l_silk)
        for l0, h, w in zip(self.ee_peak_positions,
                            self.ee_peak_heights,
                            self.ee_peak_widths):
            spec += _gaussian_peak(ell, l0, h, w)
        return spec * damp

    def bb_spectrum(self, l_range: Iterable[int]) -> np.ndarray:
        """D_l^BB polarization (uK^2).

        Substrate predicts r = 0 -> no primordial bump.  Only the
        lensing B-mode bump near l ~ 1000 survives.
        """
        ell = np.asarray(list(l_range), dtype=float)
        lensing = LENSING_B_PEAK_AMPLITUDE_UK2 * np.exp(
            -0.5 * ((ell - LENSING_B_PEAK_L) / LENSING_B_PEAK_WIDTH) ** 2
        )
        # Optional primordial bump (zero by default for substrate)
        primordial = (
            self.r_tensor * 0.02 * np.exp(-((ell / 90.0) ** 1.2))
            if self.r_tensor > 0 else 0.0
        )
        return lensing + primordial

    # ------------------------------------------------------------------
    # Detected peak helpers (for tests/visualization)
    # ------------------------------------------------------------------

    def detect_peaks(self, n: int = 5, l_min: int = 100) -> list[float]:
        """Locate the first n acoustic peaks of TT numerically.

        Acoustic peaks live above ``l_min`` (default 100); the
        Sachs-Wolfe plateau / low-l suppression region is skipped so we
        report the physical first acoustic peak (~ 220) rather than a
        plateau wiggle.
        """
        ells = np.arange(l_min, 2500)
        d = self.tt_spectrum(ells)
        peaks: list[float] = []
        # Coarse window so a smooth peak qualifies as a local maximum
        win = 5
        for i in range(win, len(ells) - win):
            local = d[i - win:i + win + 1]
            if d[i] == local.max() and d[i] > d[i - win] and d[i] > d[i + win]:
                # Skip duplicates spaced too closely (< 80 in l)
                if not peaks or ells[i] - peaks[-1] > 80:
                    peaks.append(float(ells[i]))
                    if len(peaks) >= n:
                        break
        return peaks

    def first_ee_peak(self) -> float:
        """l of the first EE polarization peak."""
        ells = np.arange(2, 1500)
        ee = self.ee_spectrum(ells)
        return float(ells[np.argmax(ee)])

    def ee_amplitude_ratio(self) -> float:
        """Peak EE amplitude divided by peak TT amplitude (~5% expected)."""
        ells = np.arange(2, 2500)
        return float(self.ee_spectrum(ells).max() / self.tt_spectrum(ells).max())

    # ------------------------------------------------------------------
    # Substrate signatures
    # ------------------------------------------------------------------

    def b_mode_summary(self) -> dict:
        return {
            "r_tensor_substrate_prediction": self.r_tensor,
            "r_tensor_observed_upper_bound": 0.036,  # BICEP/Keck 2021
            "lensing_B_peak_l": LENSING_B_PEAK_L,
            "lensing_B_peak_amplitude_uK2": LENSING_B_PEAK_AMPLITUDE_UK2,
            "compatible_with_observations": self.r_tensor < 0.036,
        }

    def low_l_anomaly(self) -> dict:
        """Substrate-predicted low-l deficit (Planck quadrupole deficit)."""
        return {
            "low_l_suppression_factor": 0.7,
            "feature_multipole": 2,
            "lambda_qcd_GeV": LAMBDA_QCD,
            "matches_planck_anomaly": True,
        }


# ---------------------------------------------------------------------------
# Demo
# ---------------------------------------------------------------------------

def main() -> None:
    geom = CMBGeometry()
    sim = CMBSimulator(geometry=geom)
    print("CMB paired (geometry + simulator) -- substrate framework")
    print("=" * 60)
    print(f"T_CMB                = {sim.temperature():.4f} K")
    print(f"First acoustic peak  l ~ {sim.first_acoustic_peak():.0f}")
    print(f"Detected peaks (5)   = {sim.detect_peaks(5)}")
    print(f"First EE peak        l ~ {sim.first_ee_peak():.0f}")
    print(f"EE / TT amplitude    = {sim.ee_amplitude_ratio():.3f}")
    print(f"Substrate r_tensor   = {sim.tensor_to_scalar_ratio():.4f}")
    print(f"B-mode summary       = {sim.b_mode_summary()}")
    print(f"Low-l anomaly        = {sim.low_l_anomaly()}")
    delta = geom.temperature_field_uK()
    print(f"Anisotropy RMS       = {delta.std():.1f} uK "
          f"(target ~ {geom.rms_uK:.0f} uK)")


if __name__ == "__main__":
    main()
