import hashlib,json,subprocess,datetime
from pathlib import Path
R=Path('/home/ubuntu/audit-repo')
def run(*a):
 p=subprocess.run(['git','-C',str(R),*a],text=True,capture_output=True); return p.returncode,p.stdout.strip(),p.stderr.strip()
def sha(p): return hashlib.sha256((R/p).read_bytes()).hexdigest()
local=run('rev-parse','HEAD')[1]; remote=run('rev-parse','origin/main')[1]; base=run('merge-base',local,remote)[1]
items=[('RC-006_EVIDENCE_PHYSICAL_INPUT_CLOSURE_PACKAGE_PROVENANCE_REPAIRED.zip','8ceb3c44b0cc14860ea0bcf5c500e71c6213556bd6d3ecf79665eb6f78f27aef'),('RC006_REPAIRED_CANONICAL_MANIFEST_FINAL.json','febffa281b5b7a63c8084c44b7554a627c579ef39f68f76805cc0790417e5e24'),('RC006_EMBEDDED_CONTENT_MANIFEST.json',None),('RC006_REPAIRED_PROVENANCE_SELF_VERIFICATION_FINAL.json',None),('RC006_PROVENANCE_REPAIR_FINAL_REPORT.json',None),('RC006_REPOSITORY_CHECKPOINT.json',None)]
arts=[]
for rel,exp in items:
 p=R/rel; tracked=run('ls-files','--error-unmatch',rel)[0]==0; committed=run('cat-file','-e','HEAD:'+rel)[0]==0
 arts.append({'path':rel,'ON_DISK':p.is_file(),'TRACKED':tracked,'COMMITTED':committed,'REACHABLE_FROM_GIT':committed,'SHA256':sha(rel) if p.exists() else None,'EXPECTED_SHA256':exp,'SHA_MATCH':p.exists() and (exp is None or sha(rel)==exp)})
push_rc=128; push_out=''; push_err="fatal: could not read Username for 'https://github.com': terminal prompts disabled"
result={'report':'GITHUB_RC006_PERSISTENCE_FORENSIC_REPORT','timestamp_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'remote':'https://github.com/NAIF-Automotive-Safety-Lab/Car-seat-engineering.git','LOCAL_HEAD':local,'REMOTE_MAIN_AT_LAST_FETCH':remote,'MERGE_BASE':base,'NON_DESTRUCTIVE_MERGE_COMMIT':'822cb3bcb9448068e092031315104b113b20cbc8','LOCAL_ONLY_COMMITS':run('rev-list','--oneline',remote+'..'+local)[1].splitlines(),'REMOTE_ONLY_COMMITS':run('rev-list','--oneline',local+'..'+remote)[1].splitlines(),'DIVERGENCE_AT_FETCH':run('rev-list','--left-right','--count',local+'...'+remote)[1],'PUSH_ATTEMPT':{'command':'git push origin main','return_code':push_rc,'stdout':push_out,'stderr':push_err,'force_push_used':False},'REMOTE_VERIFICATION':{'last_known_github_main':'460fda6b46f27f9670d97e8978e32f7cb3047fd4','authoritative_package_present':False,'external_manifest_present':False,'checkpoint_present':True,'independent_clone_verified':True},'CRITICAL_ARTIFACT_MATRIX':arts,'BASELINE_IMMUTABILITY':{'V7-R3':'UNCHANGED','R4.1':'UNCHANGED','R4.2':'ABSENT','CAD':'UNCHANGED','STEP':'UNCHANGED','GEOMETRY':'UNCHANGED','DESIGN_INTENT':'UNCHANGED','ENGINEERING_VALUES':'UNCHANGED','CAЕ_EXECUTED':False,'PHYSICAL_VALIDATION':False},'LOCAL_WORKTREE':{'status':run('status','--short','--branch')[1],'porcelain':run('status','--porcelain')[1],'untracked':run('ls-files','--others','--exclude-standard')[1]},'FINAL_VERDICT':'GITHUB_PERSISTENCE_FAILED'}
(R/'GITHUB_RC006_PERSISTENCE_FORENSIC_REPORT.json').write_text(json.dumps(result,indent=2)+'\n')
md=['# GitHub RC-006 Persistence Forensic Report','','**Final verdict:** `GITHUB_PERSISTENCE_FAILED`  ','','## Result','',f'- Local reconciled HEAD: `{local}`  ',f'- GitHub main at last fetch: `{remote}`  ',f'- Merge base: `{base}`  ',f'- Non-destructive merge commit: `822cb3bcb9448068e092031315104b113b20cbc8`  ','- No force-push, reset, rebase, squash, deletion, or history rewrite was used.','','## Push result','', '- Command: `git push origin main`', f'- Return code: `{push_rc}`', f'- Error: `{push_err}`', '- Push was blocked because GitHub credentials were unavailable in the environment.','','## Remote verification','', '- Independent GitHub clone confirmed that the authoritative RC-006 ZIP and external canonical manifest are absent from GitHub main `460fda6b46f27f9670d97e8978e32f7cb3047fd4`.', '- `RC006_REPOSITORY_CHECKPOINT.json` is present remotely, but it does not contain the authoritative package bytes.', '', '## Local artifact matrix','', '| Artifact | On disk | Tracked | Committed | Reachable | SHA match |','|---|---:|---:|---:|---:|---:|']
for a in arts: md.append(f'| `{a["path"]}` | {a["ON_DISK"]} | {a["TRACKED"]} | {a["COMMITTED"]} | {a["REACHABLE_FROM_GIT"]} | {a["SHA_MATCH"]} |')
md += ['', '## Baseline protection','', '- V7-R3 unchanged.', '- R4.1 unchanged.', '- R4.2 absent.', '- CAD/STEP/Geometry/Design Intent/Engineering Values unchanged.', '- No CAE or physical validation performed.', '', '## Required next action','', 'Enable authenticated GitHub access for this environment, then rerun the ordinary `git push origin main`. Do not use force-push.','']
(R/'GITHUB_RC006_PERSISTENCE_FORENSIC_REPORT.md').write_text('\n'.join(md))
print(json.dumps({'json':str(R/'GITHUB_RC006_PERSISTENCE_FORENSIC_REPORT.json'),'md':str(R/'GITHUB_RC006_PERSISTENCE_FORENSIC_REPORT.md'),'verdict':result['FINAL_VERDICT'],'push_error':push_err},indent=2))
