import { FlatList, StyleSheet, Text, View } from 'react-native';
import { ScreenContainer } from '@/components/screen-container';
import { IconSymbol } from '@/components/ui/icon-symbol';

const events = [
  { id: 'AUD-0007', action: 'System startup gate evaluated', detail: 'DB → API → registries → sync → drift → gap scan', time: 'Current session', state: 'BLOCKED', icon: 'lock.fill' as const },
  { id: 'AUD-0006', action: 'R4.1 mutation guard registered', detail: 'Immutable baseline policy attached; no artifact mutation allowed.', time: 'Current session', state: 'PASS', icon: 'shield.lefthalf.filled' as const },
  { id: 'AUD-0005', action: 'Gap scan opened GAP-0001', detail: 'Repository identity is missing exact branch, commit, and manifest hash.', time: 'Current session', state: 'OPEN', icon: 'exclamationmark.triangle.fill' as const },
  { id: 'AUD-0004', action: 'Engine registry loaded', detail: '20 engine definitions discovered; 6 execution paths are gated.', time: 'Current session', state: 'RECORDED', icon: 'cpu.fill' as const },
  { id: 'AUD-0003', action: 'Canonical repository binding declared', detail: 'NAIF-Automotive-Safety-Lab/Car-seat-engineering', time: 'Bootstrap', state: 'UNVERIFIED', icon: 'account-tree.fill' as const },
];

export default function AuditScreen() { return <ScreenContainer containerClassName="bg-[#08111F]" className="px-5" edges={['top', 'left', 'right']}><FlatList data={events} keyExtractor={(item) => item.id} showsVerticalScrollIndicator={false} contentContainerStyle={styles.list} ListHeaderComponent={<><Text style={styles.kicker}>PROVENANCE LAYER</Text><Text style={styles.title}>Audit trail</Text><Text style={styles.subtitle}>Every state transition leaves an attributable record.</Text><View style={styles.banner}><View style={styles.bannerIcon}><IconSymbol name="list.bullet.rectangle.portrait.fill" size={19} color="#2DE0B2" /></View><View style={{ flex: 1 }}><Text style={styles.bannerTitle}>No silent failure</Text><Text style={styles.bannerCopy}>Blocked, unknown, and unverified states stay visible until evidence changes them.</Text></View></View></>} renderItem={({ item, index }) => <View style={styles.event}><View style={styles.timeline}><View style={[styles.dot, item.state === 'BLOCKED' ? styles.dotBlocked : styles.dotOkay]} /><View style={styles.line} /></View><View style={styles.eventBody}><View style={styles.eventTop}><Text style={styles.id}>{item.id}</Text><Text style={[styles.state, { color: item.state === 'BLOCKED' || item.state === 'OPEN' ? '#FF6B76' : item.state === 'PASS' ? '#2DE0B2' : '#FFBF69' }]}>{item.state}</Text></View><View style={styles.eventTitleRow}><IconSymbol name={item.icon} size={17} color="#9FB1C4" /><Text style={styles.eventTitle}>{item.action}</Text></View><Text style={styles.detail}>{item.detail}</Text><View style={styles.eventFoot}><Text style={styles.time}>{item.time}</Text><Text style={styles.actor}>ACTOR · AEGIS KERNEL</Text></View></View></View>} /></ScreenContainer>; }

const styles = StyleSheet.create({ list: { paddingTop: 16, paddingBottom: 40 }, kicker: { color: '#8192A9', fontSize: 10, fontWeight: '800', letterSpacing: 1.4 }, title: { color: '#F5F8FC', fontSize: 28, fontWeight: '800', marginTop: 5 }, subtitle: { color: '#8192A9', fontSize: 12, marginTop: 5 }, banner: { flexDirection: 'row', gap: 11, backgroundColor: '#122B2D', borderWidth: 1, borderColor: '#23544D', borderRadius: 16, padding: 14, marginTop: 18, marginBottom: 22 }, bannerIcon: { width: 36, height: 36, borderRadius: 11, backgroundColor: '#173833', alignItems: 'center', justifyContent: 'center' }, bannerTitle: { color: '#DFFDF4', fontSize: 13, fontWeight: '800' }, bannerCopy: { color: '#92BEB1', fontSize: 10, lineHeight: 15, marginTop: 3 }, event: { flexDirection: 'row', minHeight: 118 }, timeline: { width: 27, alignItems: 'center' }, dot: { width: 10, height: 10, borderRadius: 5, borderWidth: 2, borderColor: '#08111F', marginTop: 3, zIndex: 2 }, dotBlocked: { backgroundColor: '#FF6B76' }, dotOkay: { backgroundColor: '#2DE0B2' }, line: { width: 1, flex: 1, backgroundColor: '#2A3C53', marginTop: -1 }, eventBody: { flex: 1, backgroundColor: '#101D31', borderRadius: 15, borderWidth: 1, borderColor: '#22334A', padding: 13, marginBottom: 10 }, eventTop: { flexDirection: 'row', justifyContent: 'space-between' }, id: { color: '#647891', fontSize: 9, fontWeight: '800', letterSpacing: 0.6 }, state: { fontSize: 9, fontWeight: '900', letterSpacing: 0.6 }, eventTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 10 }, eventTitle: { color: '#F5F8FC', fontSize: 12, fontWeight: '800', flex: 1 }, detail: { color: '#9DAFC2', fontSize: 10, lineHeight: 15, marginTop: 6 }, eventFoot: { flexDirection: 'row', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: '#22334A', paddingTop: 9, marginTop: 10 }, time: { color: '#647891', fontSize: 8, fontWeight: '700' }, actor: { color: '#647891', fontSize: 8, fontWeight: '700', letterSpacing: 0.3 },
});
