import { FlatList, StyleSheet, Text, View } from 'react-native';
import { ScreenContainer } from '@/components/screen-container';
import { IconSymbol } from '@/components/ui/icon-symbol';

type Engine = { id: string; name: string; version: string; status: 'REGISTERED' | 'BLOCKED'; dependency: string; tests: string; health: string };
const engines: Engine[] = [
  { id: '01', name: 'Repository Integrity', version: 'v0.1', status: 'BLOCKED', dependency: 'Git binding', tests: 'Identity / drift', health: 'GATED' },
  { id: '02', name: 'Artifact Hash / Evidence', version: 'v0.1', status: 'BLOCKED', dependency: 'Evidence store', tests: 'SHA-256 / provenance', health: 'GATED' },
  { id: '03', name: 'STEP Parser / Geometry', version: 'v0.1', status: 'BLOCKED', dependency: 'R4.1 artifact', tests: 'Schema / body records', health: 'GATED' },
  { id: '04', name: 'B-Rep Validation', version: 'v0.1', status: 'BLOCKED', dependency: 'STEP parser', tests: 'Solids / coverage', health: 'GATED' },
  { id: '05', name: 'Interface / Clearance', version: 'v0.1', status: 'BLOCKED', dependency: 'B-Rep', tests: 'Interference checks', health: 'GATED' },
  { id: '06', name: 'Kinematics', version: 'v0.1', status: 'BLOCKED', dependency: 'Constraint eval', tests: 'Motion states', health: 'GATED' },
  { id: '07', name: 'Constraint Evaluation', version: 'v0.1', status: 'REGISTERED', dependency: 'Test definitions', tests: 'Rule execution', health: 'READY' },
  { id: '08', name: 'Physics-Lite / Mechanics', version: 'v0.1', status: 'REGISTERED', dependency: 'Inputs', tests: 'Analytical checks', health: 'READY' },
  { id: '09', name: 'Trajectory / Motion', version: 'v0.1', status: 'REGISTERED', dependency: 'Kinematics', tests: 'Path replay', health: 'READY' },
  { id: '10', name: 'Parameter Sweep', version: 'v0.1', status: 'REGISTERED', dependency: 'Test definitions', tests: 'Bounds / matrix', health: 'READY' },
  { id: '11', name: 'Sensitivity / Robustness', version: 'v0.1', status: 'REGISTERED', dependency: 'Parameter sweep', tests: 'Variation analysis', health: 'READY' },
  { id: '12', name: 'Fault Injection', version: 'v0.1', status: 'REGISTERED', dependency: 'Audit gate', tests: 'Blocked-state guards', health: 'READY' },
  { id: '13', name: 'Manufacturing / Assembly', version: 'v0.1', status: 'REGISTERED', dependency: 'Geometry', tests: 'Assembly logic', health: 'READY' },
  { id: '14', name: 'Reproducibility', version: 'v0.1', status: 'REGISTERED', dependency: 'Evidence chain', tests: 'Replay identity', health: 'READY' },
  { id: '15', name: 'Evidence / Provenance', version: 'v0.1', status: 'REGISTERED', dependency: 'Evidence store', tests: 'Source lineage', health: 'READY' },
  { id: '16', name: 'Audit / Gate', version: 'v0.1', status: 'REGISTERED', dependency: 'All engines', tests: 'Decision trail', health: 'READY' },
  { id: '17', name: 'Requirements Traceability', version: 'v0.1', status: 'REGISTERED', dependency: 'Requirements', tests: 'Coverage map', health: 'READY' },
  { id: '18', name: 'Gap Detection', version: 'v0.1', status: 'REGISTERED', dependency: 'Registries', tests: 'Missing-state scan', health: 'READY' },
  { id: '19', name: 'Auto-Remediation', version: 'v0.1', status: 'REGISTERED', dependency: 'Gate rules', tests: 'Safe patch flow', health: 'READY' },
  { id: '20', name: 'Execution Orchestrator', version: 'v0.1', status: 'REGISTERED', dependency: 'All engines', tests: 'Lifecycle control', health: 'READY' },
];

export default function EnginesScreen() { return <ScreenContainer containerClassName="bg-[#08111F]" className="px-5" edges={['top', 'left', 'right']}><FlatList data={engines} keyExtractor={(item) => item.id} showsVerticalScrollIndicator={false} contentContainerStyle={styles.list} ListHeaderComponent={<View style={styles.header}><Text style={styles.kicker}>ENGINE REGISTRY</Text><Text style={styles.title}>Engine center</Text><Text style={styles.subtitle}>Execution health is separate from registration.</Text><View style={styles.summary}><View><Text style={styles.summaryValue}>20</Text><Text style={styles.summaryLabel}>REGISTERED</Text></View><View><Text style={[styles.summaryValue, { color: '#FF6B76' }]}>6</Text><Text style={styles.summaryLabel}>BLOCKED</Text></View><View><Text style={[styles.summaryValue, { color: '#2DE0B2' }]}>14</Text><Text style={styles.summaryLabel}>READY</Text></View></View></View>} renderItem={({ item }) => <View style={styles.card}><View style={styles.engineTop}><View style={styles.engineId}><Text style={styles.id}>{item.id}</Text><View style={[styles.engineIcon, item.status === 'BLOCKED' ? styles.blockedIcon : styles.readyIcon]}><IconSymbol name="cpu.fill" size={16} color={item.status === 'BLOCKED' ? '#FF6B76' : '#2DE0B2'} /></View><View><Text style={styles.name}>{item.name}</Text><Text style={styles.version}>{item.version} · {item.tests}</Text></View></View><Text style={[styles.status, { color: item.status === 'BLOCKED' ? '#FF6B76' : '#2DE0B2' }]}>{item.status}</Text></View><View style={styles.engineMeta}><Text style={styles.dep}>DEPENDENCY · <Text style={styles.depValue}>{item.dependency}</Text></Text><Text style={[styles.health, { color: item.status === 'BLOCKED' ? '#FFBF69' : '#2DE0B2' }]}>{item.health}</Text></View></View>} /></ScreenContainer>; }

const styles = StyleSheet.create({ list: { paddingTop: 16, paddingBottom: 40, gap: 10 }, header: { marginBottom: 7 }, kicker: { color: '#8192A9', fontSize: 10, fontWeight: '800', letterSpacing: 1.4 }, title: { color: '#F5F8FC', fontSize: 28, fontWeight: '800', marginTop: 5 }, subtitle: { color: '#8192A9', fontSize: 12, marginTop: 5 }, summary: { flexDirection: 'row', gap: 34, marginTop: 20, paddingBottom: 7 }, summaryValue: { color: '#DCE7F2', fontSize: 22, fontWeight: '900' }, summaryLabel: { color: '#687A91', fontSize: 8, fontWeight: '900', letterSpacing: 0.9, marginTop: 3 }, card: { backgroundColor: '#101D31', borderRadius: 15, borderWidth: 1, borderColor: '#22334A', padding: 13 }, engineTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, engineId: { flexDirection: 'row', alignItems: 'center', gap: 9, flex: 1 }, id: { color: '#647891', fontSize: 10, fontWeight: '800', width: 18 }, engineIcon: { width: 32, height: 32, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, blockedIcon: { backgroundColor: '#2B2331' }, readyIcon: { backgroundColor: '#173833' }, name: { color: '#F5F8FC', fontSize: 12, fontWeight: '800' }, version: { color: '#74869C', fontSize: 9, marginTop: 3 }, status: { fontSize: 9, fontWeight: '900', letterSpacing: 0.5 }, engineMeta: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderTopWidth: 1, borderTopColor: '#22334A', marginTop: 11, paddingTop: 9 }, dep: { color: '#647891', fontSize: 8, fontWeight: '800', letterSpacing: 0.4 }, depValue: { color: '#AFC0D4', fontWeight: '700' }, health: { fontSize: 9, fontWeight: '900' },
});
