import AsyncStorage from '@react-native-async-storage/async-storage';
import { useEffect, useState } from 'react';
import { FlatList, Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import * as Haptics from 'expo-haptics';

import { ScreenContainer } from '@/components/screen-container';
import { IconSymbol } from '@/components/ui/icon-symbol';

 type Gap = { id: string; title: string; description: string; source: string; severity: 'P0' | 'P1'; dependency: string; auto: boolean; status: 'OPEN' | 'QUEUED'; evidence: string; owner: string };
const seedGaps: Gap[] = [
  { id: 'GAP-0001', title: 'Canonical repository identity', description: 'Exact branch, commit, and manifest hash have not been verified.', source: 'Repository Integrity', severity: 'P0', dependency: 'Git binding', auto: false, status: 'OPEN', evidence: 'BLOCKED', owner: 'Unassigned' },
  { id: 'GAP-0002', title: 'R4.1 artifact unavailable', description: 'The immutable qualification artifact is not attached to a verified source.', source: 'Artifact Integrity', severity: 'P0', dependency: 'GAP-0001', auto: false, status: 'OPEN', evidence: 'BLOCKED', owner: 'Unassigned' },
  { id: 'GAP-0003', title: 'Qualification run not reproducible', description: 'No run record contains commit, model hash, inputs, and engine version together.', source: 'Reproducibility', severity: 'P1', dependency: 'GAP-0002', auto: true, status: 'OPEN', evidence: 'UNVERIFIED', owner: 'ETSE' },
  { id: 'GAP-0004', title: 'Remote sync proof missing', description: 'LOCAL HEAD == REMOTE HEAD has not been demonstrated for the bound repository.', source: 'Sync Gate', severity: 'P1', dependency: 'GAP-0001', auto: true, status: 'OPEN', evidence: 'UNVERIFIED', owner: 'Git Sync' },
];

export default function GapsScreen() {
  const [gaps, setGaps] = useState(seedGaps);
  useEffect(() => { AsyncStorage.getItem('aegis.queuedGaps').then((raw) => { if (raw) { const queued = JSON.parse(raw) as string[]; setGaps(seedGaps.map((gap) => queued.includes(gap.id) ? { ...gap, status: 'QUEUED' } : gap)); } }); }, []);
  const queueRepair = async (id: string) => {
    const next = gaps.map((gap) => gap.id === id ? { ...gap, status: 'QUEUED' as const } : gap);
    setGaps(next);
    await AsyncStorage.setItem('aegis.queuedGaps', JSON.stringify(next.filter((gap) => gap.status === 'QUEUED').map((gap) => gap.id)));
    if (Platform.OS !== 'web') await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
  };

  return <ScreenContainer containerClassName="bg-[#08111F]" className="px-5" edges={['top', 'left', 'right']}><FlatList data={gaps} keyExtractor={(item) => item.id} showsVerticalScrollIndicator={false} contentContainerStyle={styles.list} ListHeaderComponent={<><View style={styles.header}><View><Text style={styles.kicker}>CONTROL CENTER</Text><Text style={styles.title}>Gap center</Text><Text style={styles.subtitle}>Open issues that prevent an honest system gate.</Text></View><View style={styles.count}><Text style={styles.countValue}>{gaps.filter((gap) => gap.status === 'OPEN').length}</Text><Text style={styles.countLabel}>OPEN</Text></View></View><View style={styles.rule}><IconSymbol name="lock.fill" size={15} color="#FFBF69" /><Text style={styles.ruleText}>A gap cannot close without fresh verification evidence.</Text></View></>} renderItem={({ item }) => <View style={styles.card}><View style={styles.cardTop}><View style={styles.idRow}><Text style={styles.id}>{item.id}</Text><View style={[styles.severity, item.severity === 'P0' ? styles.p0 : styles.p1]}><Text style={styles.severityText}>{item.severity}</Text></View></View><View style={[styles.status, item.status === 'QUEUED' ? styles.queued : styles.open]}><Text style={styles.statusText}>{item.status}</Text></View></View><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.description}>{item.description}</Text><View style={styles.metaGrid}><View><Text style={styles.metaLabel}>SOURCE</Text><Text style={styles.metaValue}>{item.source}</Text></View><View><Text style={styles.metaLabel}>DEPENDENCY</Text><Text style={styles.metaValue}>{item.dependency}</Text></View><View><Text style={styles.metaLabel}>EVIDENCE</Text><Text style={[styles.metaValue, { color: item.evidence === 'BLOCKED' ? '#FF6B76' : '#FFBF69' }]}>{item.evidence}</Text></View></View><View style={styles.bottomRow}><Text style={styles.owner}>OWNER · {item.owner}</Text>{item.status === 'QUEUED' ? <Text style={styles.queuedLabel}>QUEUED FOR VERIFIED RUN</Text> : <Pressable disabled={!item.auto} onPress={() => queueRepair(item.id)} style={({ pressed }) => [styles.repairButton, !item.auto && styles.disabled, pressed && styles.pressed]}><IconSymbol name="hammer.fill" size={14} color={item.auto ? '#08111F' : '#687A91'} /><Text style={[styles.repairText, !item.auto && { color: '#687A91' }]}>{item.auto ? 'QUEUE REPAIR' : 'MANUAL INPUT'}</Text></Pressable>}</View></View>} /></ScreenContainer>;
}

const styles = StyleSheet.create({ list: { paddingTop: 16, paddingBottom: 40, gap: 13 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 17 }, kicker: { color: '#8192A9', fontSize: 10, fontWeight: '800', letterSpacing: 1.4 }, title: { color: '#F5F8FC', fontSize: 28, fontWeight: '800', marginTop: 5 }, subtitle: { color: '#8192A9', fontSize: 12, marginTop: 5 }, count: { alignItems: 'center', backgroundColor: '#412733', borderRadius: 15, paddingHorizontal: 13, paddingVertical: 10 }, countValue: { color: '#FF6B76', fontSize: 22, fontWeight: '900' }, countLabel: { color: '#F28B97', fontSize: 9, fontWeight: '900', letterSpacing: 1 }, rule: { flexDirection: 'row', alignItems: 'center', gap: 9, backgroundColor: '#2B2925', borderRadius: 12, padding: 12, borderWidth: 1, borderColor: '#4A402F' }, ruleText: { color: '#D9C19A', flex: 1, fontSize: 11, lineHeight: 16 }, card: { backgroundColor: '#101D31', borderRadius: 17, borderWidth: 1, borderColor: '#22334A', padding: 15 }, cardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, idRow: { flexDirection: 'row', alignItems: 'center', gap: 8 }, id: { color: '#7F9AB5', fontSize: 10, fontWeight: '800', letterSpacing: 0.7 }, severity: { borderRadius: 5, paddingHorizontal: 6, paddingVertical: 3 }, p0: { backgroundColor: '#412733' }, p1: { backgroundColor: '#332E27' }, severityText: { color: '#FFBF69', fontSize: 9, fontWeight: '900' }, status: { borderRadius: 6, paddingHorizontal: 7, paddingVertical: 4 }, open: { backgroundColor: '#2B2331' }, queued: { backgroundColor: '#173833' }, statusText: { color: '#FF6B76', fontSize: 9, fontWeight: '900', letterSpacing: 0.5 }, cardTitle: { color: '#F5F8FC', fontSize: 15, fontWeight: '800', marginTop: 12 }, description: { color: '#9DAFC2', fontSize: 11, lineHeight: 17, marginTop: 5 }, metaGrid: { flexDirection: 'row', gap: 18, borderTopWidth: 1, borderTopColor: '#22334A', marginTop: 14, paddingTop: 12 }, metaLabel: { color: '#667A92', fontSize: 8, fontWeight: '800', letterSpacing: 0.8 }, metaValue: { color: '#C6D3E1', fontSize: 10, fontWeight: '700', marginTop: 4, maxWidth: 100 }, bottomRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 15 }, owner: { color: '#687A91', fontSize: 9, fontWeight: '700' }, queuedLabel: { color: '#2DE0B2', fontSize: 9, fontWeight: '900', letterSpacing: 0.4 }, repairButton: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#2DE0B2', borderRadius: 8, paddingHorizontal: 9, paddingVertical: 7 }, repairText: { color: '#08111F', fontSize: 9, fontWeight: '900' }, disabled: { backgroundColor: '#202C3D' }, pressed: { opacity: 0.7 },
});
