import { ActivityIndicator, FlatList, StyleSheet, Text, View } from 'react-native';
import { ScreenContainer } from '@/components/screen-container';
import { IconSymbol } from '@/components/ui/icon-symbol';
import { trpc } from '@/lib/trpc';

type KernelState = 'BLOCKED' | 'QUEUED' | 'RUNNING' | 'COMPLETED' | 'FAILED' | 'NOT_PROVEN';
type Run = { runId: string; testId: string; testVersion: string; state: KernelState; blockReason: string | null; gate: string };
const tone: Record<KernelState, string> = { BLOCKED: '#FF6B76', QUEUED: '#FFBF69', RUNNING: '#2DE0B2', COMPLETED: '#2DE0B2', FAILED: '#FF6B76', NOT_PROVEN: '#8DA0B8' };

export default function RunsScreen() {
  const status = trpc.kernel.status.useQuery(undefined, { retry: false, refetchOnMount: 'always' });
  const runs = (status.data?.runs ?? []) as Run[];
  const unavailable = Boolean(status.error);
  return <ScreenContainer containerClassName="bg-[#08111F]" className="px-5" edges={['top', 'left', 'right']}>
    <FlatList data={runs} keyExtractor={(item) => item.runId} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><Text style={styles.eyebrow}>EXECUTION BUS</Text><Text style={styles.title}>Kernel runs</Text><Text style={styles.subtitle}>Live data from AEGIS-X. The UI can inspect runs; only the trusted kernel may execute them.</Text><View style={styles.policy}><IconSymbol name="shield.lefthalf.filled" size={18} color="#2DE0B2" /><View><Text style={styles.policyTitle}>No silent skip</Text><Text style={styles.policyCopy}>Every blocked or unverified state remains visible.</Text></View></View><View style={styles.legend}><Text style={styles.legendText}>REGISTERED</Text><Text style={styles.legendText}>EXECUTED</Text><Text style={styles.legendText}>VERIFIED</Text><Text style={styles.legendText}>PASS</Text></View>{status.isLoading && <View style={styles.notice}><ActivityIndicator color="#2DE0B2" /><Text style={styles.noticeText}>Loading kernel state…</Text></View>}{unavailable && <View style={styles.blockedNotice}><Text style={styles.blockedTitle}>KERNEL READ BLOCKED</Text><Text style={styles.blockedCopy}>Authenticated backend access is required. No local fixture is substituted.</Text></View>}{!status.isLoading && !unavailable && runs.length === 0 && <View style={styles.notice}><Text style={styles.noticeText}>No persisted kernel runs.</Text></View>}</View>} renderItem={({ item }) => <View style={styles.card}><View style={styles.cardTop}><Text style={styles.id}>{item.runId}</Text><Text style={[styles.state, { color: tone[item.state] }]}>{item.state}</Text></View><Text style={styles.test}>{item.testId} · {item.testVersion}</Text><Text style={styles.detail}>{item.blockReason ?? 'No block reason recorded; inspect evidence and gate.'}</Text><View style={styles.divider} /><Text style={styles.gate}>{item.gate}</Text></View>} />
  </ScreenContainer>;
}

const styles = StyleSheet.create({ content: { paddingTop: 16, paddingBottom: 38, gap: 12 }, header: { gap: 7, marginBottom: 4 }, eyebrow: { color: '#8DA0B8', fontSize: 9, fontWeight: '900', letterSpacing: 1.4 }, title: { color: '#F5F8FC', fontSize: 27, fontWeight: '900' }, subtitle: { color: '#8192A9', fontSize: 11, lineHeight: 17 }, policy: { flexDirection: 'row', gap: 11, alignItems: 'center', backgroundColor: '#12352F', borderColor: '#1E6C5B', borderWidth: 1, borderRadius: 15, padding: 13, marginTop: 8 }, policyTitle: { color: '#D9FFF5', fontWeight: '900', fontSize: 12 }, policyCopy: { color: '#8DC9BC', fontSize: 10, marginTop: 3 }, legend: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8 }, legendText: { color: '#667991', fontSize: 8, fontWeight: '800', letterSpacing: 0.6 }, notice: { flexDirection: 'row', gap: 8, alignItems: 'center', backgroundColor: '#0E1A2B', borderRadius: 12, padding: 11, marginTop: 4 }, noticeText: { color: '#8DA0B8', fontSize: 10 }, blockedNotice: { backgroundColor: '#33232B', borderColor: '#5B3440', borderWidth: 1, borderRadius: 12, padding: 11, marginTop: 4 }, blockedTitle: { color: '#FF6B76', fontSize: 10, fontWeight: '900' }, blockedCopy: { color: '#C79CA5', fontSize: 10, lineHeight: 15, marginTop: 4 }, card: { backgroundColor: '#101D31', borderColor: '#22334A', borderWidth: 1, borderRadius: 16, padding: 14, gap: 7 }, cardTop: { flexDirection: 'row', justifyContent: 'space-between' }, id: { color: '#8DA0B8', fontSize: 9, fontWeight: '900', letterSpacing: 1 }, state: { fontSize: 9, fontWeight: '900', letterSpacing: 0.7 }, test: { color: '#F5F8FC', fontSize: 14, fontWeight: '900' }, detail: { color: '#A0B0C2', fontSize: 11, lineHeight: 17 }, divider: { height: 1, backgroundColor: '#22334A', marginTop: 3 }, gate: { color: '#FFBF69', fontSize: 9, fontWeight: '900', letterSpacing: 0.7 },
});
