import { ActivityIndicator, FlatList, StyleSheet, Text, View } from 'react-native';
import { ScreenContainer } from '@/components/screen-container';
import { IconSymbol } from '@/components/ui/icon-symbol';
import { trpc } from '@/lib/trpc';

type Contract = { testId: string; version: string; engineId: string; evidenceClass: string; gatePolicy: string; checks: string };

export default function TestsScreen() {
  const status = trpc.kernel.status.useQuery(undefined, { retry: false, refetchOnMount: 'always' });
  const contracts = (status.data?.tests ?? []) as Contract[];
  const unavailable = Boolean(status.error);
  return <ScreenContainer containerClassName="bg-[#08111F]" className="px-5" edges={['top', 'left', 'right']}>
    <FlatList data={contracts} keyExtractor={(item) => item.testId} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><Text style={styles.eyebrow}>CONTRACT REGISTRY</Text><Text style={styles.title}>Tests</Text><Text style={styles.subtitle}>Live versioned contracts from AEGIS-X. A contract is not a result.</Text>{status.isLoading && <View style={styles.notice}><ActivityIndicator color="#2DE0B2" /><Text style={styles.noticeText}>Loading test registry…</Text></View>}{unavailable && <View style={styles.blockedNotice}><Text style={styles.blockedTitle}>REGISTRY READ BLOCKED</Text><Text style={styles.blockedCopy}>Authenticated backend access is required. No fixture contracts are substituted.</Text></View>}{!status.isLoading && !unavailable && contracts.length === 0 && <View style={styles.notice}><Text style={styles.noticeText}>No persisted test contracts.</Text></View>}</View>} renderItem={({ item }) => <View style={styles.card}><View style={styles.cardTop}><View style={styles.icon}><IconSymbol name="checkmark.seal.fill" size={17} color="#2DE0B2" /></View><View style={styles.heading}><Text style={styles.id}>{item.testId}</Text><Text style={styles.version}>{item.version} · REGISTERED</Text></View></View><Text style={styles.engine}>ENGINE · {item.engineId}</Text><Text style={styles.checks}>{item.checks || 'Checks are defined by the persisted contract.'}</Text><View style={styles.footer}><Text style={styles.evidence}>EVIDENCE · {item.evidenceClass}</Text><Text style={styles.gate}>GATE POLICY · {item.gatePolicy}</Text></View></View>} />
  </ScreenContainer>;
}

const styles = StyleSheet.create({ content: { paddingTop: 16, paddingBottom: 38, gap: 12 }, header: { gap: 7, marginBottom: 4 }, eyebrow: { color: '#8DA0B8', fontSize: 9, fontWeight: '900', letterSpacing: 1.4 }, title: { color: '#F5F8FC', fontSize: 27, fontWeight: '900' }, subtitle: { color: '#8192A9', fontSize: 11, lineHeight: 17 }, notice: { flexDirection: 'row', gap: 8, alignItems: 'center', backgroundColor: '#0E1A2B', borderRadius: 12, padding: 11, marginTop: 4 }, noticeText: { color: '#8DA0B8', fontSize: 10 }, blockedNotice: { backgroundColor: '#33232B', borderColor: '#5B3440', borderWidth: 1, borderRadius: 12, padding: 11, marginTop: 4 }, blockedTitle: { color: '#FF6B76', fontSize: 10, fontWeight: '900' }, blockedCopy: { color: '#C79CA5', fontSize: 10, lineHeight: 15, marginTop: 4 }, card: { backgroundColor: '#101D31', borderColor: '#22334A', borderWidth: 1, borderRadius: 16, padding: 14, gap: 10 }, cardTop: { flexDirection: 'row', gap: 10, alignItems: 'center' }, icon: { width: 34, height: 34, borderRadius: 11, backgroundColor: '#173833', alignItems: 'center', justifyContent: 'center' }, heading: { flex: 1 }, id: { color: '#F5F8FC', fontSize: 13, fontWeight: '900' }, version: { color: '#2DE0B2', fontSize: 9, fontWeight: '900', marginTop: 3, letterSpacing: 0.6 }, engine: { color: '#FFBF69', fontSize: 9, fontWeight: '900', letterSpacing: 0.7 }, checks: { color: '#A0B0C2', fontSize: 11, lineHeight: 17 }, footer: { borderTopColor: '#22334A', borderTopWidth: 1, paddingTop: 9, gap: 5 }, evidence: { color: '#8DA0B8', fontSize: 8, fontWeight: '800', letterSpacing: 0.6 }, gate: { color: '#FF6B76', fontSize: 8, fontWeight: '900', letterSpacing: 0.6 },
});
