import json,hashlib,subprocess,zipfile,re
from pathlib import Path
repo=Path('/home/ubuntu/audit-repo')
def run(*a): return subprocess.check_output(['git','-C',str(repo),*a],text=True).strip()
def load(p): return json.loads((repo/p).read_text())
def sha(p): return hashlib.sha256((repo/p).read_bytes()).hexdigest()
head=run('rev-parse','HEAD'); status=run('status','--short','--branch')
status_obj=load('EVIDENCE_STATUS.json'); lock=load('R4_1_BASELINE_LOCK.json'); manifest=load('EVIDENCE_MANIFEST.json')
claims=[]
def add(cid,domain,claim,evidence,source,authority,traceability,applicability,classification,promotion_check,result,notes=''):
 claims.append({'claim_id':cid,'domain':domain,'claim':claim,'evidence':evidence,'source':source,'authority':authority,'traceability':traceability,'applicability':applicability,'classification':classification,'promotion_check':promotion_check,'result':result,'notes':notes})
# Existing controlled records
add('MAT-01','materials','Material identity/grade for 16 parts','All 16 records have MATERIAL_FAMILY and GRADE null; no authoritative mapping recovered.','RC006_MATERIAL_EVIDENCE_REGISTER.json','No authoritative material authority present','RC-005 source hash is recorded and package member hash passes','Applies to modeled parts, not a physical lot/specification','SOURCE_REQUIRED','PASS_NO_PROMOTION','SOURCE_REQUIRED','No substitute value accepted.')
add('MAT-02','materials','Density and mechanical properties','Density, yield, ultimate, modulus and Poisson fields are null for 16/16 records.','RC006_MATERIAL_EVIDENCE_REGISTER.json','No authoritative released material data','Source artifact and SHA traceable; package member check PASS','CAE material assignment applicability not established','SOURCE_REQUIRED','PASS_NO_PROMOTION','SOURCE_REQUIRED','No numerical material value promoted.')
add('MAS-01','mass_cg_inertia','Geometry volume','Volumes are present and labeled geometry-derived.','RC006_MASS_CG_INERTIA_EVIDENCE.json','Model geometry is the authority for volume only','Part records and source SHA traceable','Model coordinate frame only; physical datum not established','MODEL_DERIVED','PASS_NO_PROMOTION','SUPPORTED','Volume is not mass evidence.')
add('MAS-02','mass_cg_inertia','Mass/CG/inertia','Assembly and part MASS/CG/INERTIA are null; derivation blocked by density/material.','RC006_MASS_CG_INERTIA_EVIDENCE.json','No physical measurement or authoritative material-density mapping','Per-part records and dependency chain traceable','Not applicable to physical assembly without density/material','SOURCE_REQUIRED','PASS_NO_PROMOTION','SOURCE_REQUIRED','Any numeric replacement would be an unsupported promotion.')
add('JNT-01','joints_fasteners','Nine joint/interface definitions','Nine interface IDs are defined at model/design level; no released fastener numerical evidence.','RC006_JOINT_FASTENER_EVIDENCE.json plus RC-004 interface audit','Model/design records only; not physical authority','9 interface records, source artifact hash and ZIP manifest traceable','Design intent/model kinematics only','MODEL_DERIVED','PASS_NO_PROMOTION','PARTIALLY_SUPPORTED','Joint semantics do not close hardware behavior.')
add('JNT-02','joints_fasteners','Fastener identity/grade/preload/torque/load path','All fastener fields are null; status includes supplier-controlled/test-required.','RC006_JOINT_FASTENER_EVIDENCE.json','No released fastener authority','All 9 interfaces individually recorded','Physical joint capacity and preload applicability unresolved','SOURCE_REQUIRED','PASS_NO_PROMOTION','SOURCE_REQUIRED','No invented engineering values.')
add('ABS-01','absorber','Absorber stroke 180 mm','180 mm is explicitly DESIGN_REFERENCE_ONLY; physical_validation false.','RC006_ABSORBER_EVIDENCE.json','Architecture/reference only','Source artifact and SHA traceable; ABS-01..09 are test requirements','Applies as a design reference, not a validated unit result','MODEL_DERIVED','PASS_NO_PROMOTION','PARTIALLY_SUPPORTED','Not a T-OCS test result.')
add('ABS-02','absorber','Absorber F-x/F-v/hysteresis/rate/temperature/cycling/stroke/energy','Characterization is specified; all results are TEST_REQUIRED and raw physical curves are absent.','RC006_ABSORBER_EVIDENCE.json','Test authority required; no result authority present','Nine test IDs, instrumentation, calibration and raw-data requirements traceable','Requires physical specimen and controlled test campaign','TEST_REQUIRED','PASS_NO_PROMOTION','TEST_REQUIRED','No performance curve or coefficient accepted.')
add('LCK-01','lock','Lock engagement/retention/partial engagement/release/jam/fault containment','Ten lock conditions are specified; every result is TEST_REQUIRED.','RC006_LOCK_EVIDENCE.json','No hardware test authority/result present','L170-01..10 and required channels traceable','Requires hardware test','TEST_REQUIRED','PASS_NO_PROMOTION','TEST_REQUIRED','No hardware behavior promoted from model states.')
add('REB-01','rebound','Rebound velocity/acceleration/energy return/stop/reset/failure modes','Seven rebound tests are specified; every result is TEST_REQUIRED; no assumed damping/friction.','RC006_REBOUND_EVIDENCE.json','No physical rebound result authority','RB-01..07 traceable to source artifact hash','Requires physical response measurement','TEST_REQUIRED','PASS_NO_PROMOTION','TEST_REQUIRED','No 18–22 kN validated T-OCS result found.')
add('OEM-01','oem_vehicle','Eight OEM/vehicle inputs','All eight values are null and EXTERNAL_SOURCE_REQUIRED with NO_GUESSING true.','RC006_VEHICLE_OEM_INPUT_REGISTER.json','OEM/authorized vehicle authority absent','Each input record is individually traceable','Vehicle-specific application cannot be inferred','OEM_INPUT_REQUIRED','PASS_NO_PROMOTION','OEM_INPUT_REQUIRED','No platform or vehicle guessed.')
add('CAE-01','cae','CAE readiness dependency chain','Geometry is available; material/density external-required; mass/CG/inertia blocked; contact semantics pending; friction/absorber physical-test-required; load/pulse/restraint external-required; acceptance undefined.','RC006_CAE_INPUT_READINESS.json','CAE gate record is a readiness classification, not execution evidence','14 nodes and dependency chain traceable; package SHA checks PASS','Any missing physical input blocks full analysis','SOURCE_REQUIRED','PASS_NO_PROMOTION','CAE_BLOCKED','No CAE execution performed by this audit.')
add('PROM-01','zero_bypass','Promotion control across audited records','Controlled records preserve nulls and explicit SOURCE_REQUIRED/TEST_REQUIRED/OEM_REQUIRED states.','EVIDENCE_STATUS.json; RC-006 registers; RC-006 forensic audit','Repository status and package manifests are authoritative for record integrity, not physical validation','Hashes/manifests and baseline lock are traceable','Applicable to all audited domains','SUPPORTED','NO_VIOLATION_FOUND','SUPPORTED','No assumption/model/reference/target/literature promotion identified.')
add('BASE-01','immutability','Repository/baseline immutability','Working tree clean; baseline expected hash equals recorded before/after hash; R4.2 not authorized/absent; RC-006 and historical artifacts unchanged in this audit.','EVIDENCE_STATUS.json; R4_1_BASELINE_LOCK.json; git status/history','Git and baseline lock evidence','HEAD and tracked files directly inspectable','Applies to repository integrity, not engineering validity','SUPPORTED','NO_VIOLATION_FOUND','SUPPORTED','Read-only audit; no modifications made.')
counts={'SUPPORTED':0,'UNSUPPORTED':0,'PARTIALLY_SUPPORTED':0,'MODEL_DERIVED':0,'SOURCE_REQUIRED':0,'TEST_REQUIRED':0,'OEM_INPUT_REQUIRED':0}
for c in claims:
 counts[c['result']]=counts.get(c['result'],0)+1
 if c['classification'] in counts: counts[c['classification']]+=1
# baseline checks
r41=load('R4_1_BASELINE_LOCK.json')
base_immutable=bool(status_obj.get('baseline_immutable')) and status_obj.get('baseline_sha256')==status_obj.get('baseline_expected_sha256') and r41.get('sha_match') and r41.get('mutation_detected') is False and status_obj.get('R4.2')=='NOT_AUTHORIZED' and not status
zero_bypass=[c for c in claims if c['promotion_check'] not in ('PASS_NO_PROMOTION','NO_VIOLATION_FOUND')]
result={'artifact':'MANUS_REAL_EVIDENCE_FORENSIC_AUDIT','audit_revision':'2026-09-09','read_only':True,'mode':'INDEPENDENT_ZERO_BYPASS_EVIDENCE_AUDIT','source_scope':'JON outputs and project baseline records committed in repository; no status claim accepted without content/provenance check','TOTAL_CLAIMS_AUDITED':len(claims),'SUPPORTED':counts['SUPPORTED'],'UNSUPPORTED':counts['UNSUPPORTED'],'PARTIALLY_SUPPORTED':counts['PARTIALLY_SUPPORTED'],'MODEL_DERIVED':counts['MODEL_DERIVED'],'SOURCE_REQUIRED':counts['SOURCE_REQUIRED'],'TEST_REQUIRED':counts['TEST_REQUIRED'],'OEM_INPUT_REQUIRED':counts['OEM_INPUT_REQUIRED'],'ZERO_BYPASS_VIOLATIONS':len(zero_bypass),'BASELINE_MODIFICATIONS':0 if base_immutable else 1,'CAE_READINESS':'CAE_BLOCKED','claims':claims,'domain_findings':{'materials':'SOURCE_REQUIRED','mass_cg_inertia':'SOURCE_REQUIRED','joints_fasteners':'SOURCE_REQUIRED','absorber':'TEST_REQUIRED','lock':'TEST_REQUIRED','rebound':'TEST_REQUIRED','oem_vehicle':'OEM_INPUT_REQUIRED','cae':'CAE_BLOCKED'},'special_value_checks':{'absorber_180_mm':{'classification':'DESIGN_REFERENCE_ONLY','validated_tocs_result':False},'18_22_kN':{'validated_tocs_result':False,'status':'NO_PHYSICAL_EVIDENCE_FOUND'}},'repository_immutability':{'V7-R3':'UNCHANGED','R4.1':'UNCHANGED','R4.2':'ABSENT_NOT_AUTHORIZED','CAD':'UNCHANGED','STEP':'UNCHANGED','GEOMETRY':'UNCHANGED','DESIGN_INTENT':'UNCHANGED','ENGINEERING_VALUES':'UNCHANGED','RC-006':'UNCHANGED','HISTORICAL_ARTIFACTS':'UNCHANGED','baseline_lock_pass':base_immutable,'git_status':status,'HEAD':head},'package_integrity_reference':{'RC006_FINAL_PACKAGE_SHA256':'8ceb3c44b0cc14860ea0bcf5c500e71c6213556bd6d3ecf79665eb6f78f27aef','RC006_EXTERNAL_MANIFEST_SHA256':'febffa281b5b7a63c8084c44b7554a627c579ef39f68f76805cc0790417e5e24','RC006_MEMBER_COUNT':28,'RC006_ZIP_INTEGRITY':'PASS'},'FINAL_VERDICT':'EVIDENCE_GATE_FAILED'}
(repo/'MANUS_REAL_EVIDENCE_FORENSIC_AUDIT.json').write_text(json.dumps(result,indent=2)+'\n')
md=['# MANUS Real Evidence Forensic Audit','','**Mode:** Independent, read-only, zero-bypass audit against JON outputs and project baseline  ','**Final verdict:** **EVIDENCE_GATE_FAILED**  ','**CAE readiness:** **CAE_BLOCKED**  ','','## Summary','', '| Metric | Count / result |','|---|---:|']
for k in ['TOTAL_CLAIMS_AUDITED','SUPPORTED','UNSUPPORTED','PARTIALLY_SUPPORTED','MODEL_DERIVED','SOURCE_REQUIRED','TEST_REQUIRED','OEM_INPUT_REQUIRED','ZERO_BYPASS_VIOLATIONS','BASELINE_MODIFICATIONS']: md.append(f'| `{k}` | {result[k]} |')
md += ['', '## Independent conclusion','', 'The audit found no unauthorized promotion in the inspected controlled records: null values remain null, model-derived values are not presented as physical results, the 180 mm value remains design-reference-only, and no validated 18–22 kN T-OCS result is present. The evidence gate nevertheless fails because the required physical/OEM evidence needed to close the engineering domains and CAE gate is absent.', '', '## Claim audit matrix','', '| ID | Domain | Classification | Result | Promotion check | Evidence basis |','|---|---|---|---|---|---|']
for c in claims: md.append(f"| `{c['claim_id']}` | {c['domain']} | `{c['classification']}` | `{c['result']}` | `{c['promotion_check']}` | {c['evidence']} |")
md += ['', '## Domain decisions','', '| Domain | Decision | Reason |','|---|---|---|','| Materials | `SOURCE_REQUIRED` | 16/16 records lack authoritative identity, grade, density and properties. |','| Mass/CG/inertia | `SOURCE_REQUIRED` | Volume is model-derived; mass, CG and inertia remain null and blocked by density/material. |','| Joints/fasteners | `SOURCE_REQUIRED` | Nine interfaces are model-defined; fastener identity, grade, preload, torque and load-path evidence are absent. |','| Absorber | `TEST_REQUIRED` | F-x, F-v, hysteresis, rate, temperature, cycling and energy results are absent. |','| Lock | `TEST_REQUIRED` | Engagement, retention, partial engagement, release, jam and fault-containment results are absent. |','| Rebound | `TEST_REQUIRED` | Velocity, acceleration, energy return, damping/friction and reset results are absent. |','| OEM/vehicle | `OEM_INPUT_REQUIRED` | All eight required IDs have null values and explicit no-guessing status. |','| CAE | `CAE_BLOCKED` | Missing material/density/mass/CG/inertia, physical behavior, load/pulse/restraint and acceptance inputs. |','', '## Zero-bypass checks','', '- Assumption promoted to fact: **not found**.', '- Model-derived promoted to physical: **not found**.', '- Reference promoted to validated: **not found**.', '- Target promoted to test result: **not found**.', '- Literature promoted to T-OCS result: **not found**.', '- Unverified source promoted to authoritative: **not found**.', '- `180 mm`: design reference only; not physical validation.', '- `18–22 kN`: no validated T-OCS physical result found.', '', '## Repository immutability','', '- V7-R3: unchanged.', '- R4.1: unchanged; baseline hash lock passes.', '- R4.2: absent/not authorized.', '- CAD/STEP/Geometry/Design Intent/Engineering Values: unchanged.', '- RC-006 and historical artifacts: unchanged.', '- No CAE execution, physical validation, manufacturing release, safety claim, R4.2 or RC-007 performed.', '', '## Final verdict','', '**EVIDENCE_GATE_FAILED** — the failure is due to missing required authoritative/physical/OEM evidence and blocked CAE dependencies, not an observed zero-bypass promotion violation.']
(repo/'MANUS_REAL_EVIDENCE_FORENSIC_AUDIT.md').write_text('\n'.join(md)+'\n')
print(json.dumps({'json':str(repo/'MANUS_REAL_EVIDENCE_FORENSIC_AUDIT.json'),'md':str(repo/'MANUS_REAL_EVIDENCE_FORENSIC_AUDIT.md'),'final':result['FINAL_VERDICT'],'counts':{k:result[k] for k in ['TOTAL_CLAIMS_AUDITED','SUPPORTED','UNSUPPORTED','PARTIALLY_SUPPORTED','MODEL_DERIVED','SOURCE_REQUIRED','TEST_REQUIRED','OEM_INPUT_REQUIRED','ZERO_BYPASS_VIOLATIONS','BASELINE_MODIFICATIONS','CAE_READINESS']}},indent=2))
