import json,hashlib,subprocess,zipfile
from pathlib import Path
repo=Path('/home/ubuntu/audit-repo')
def run(*a): return subprocess.check_output(['git','-C',str(repo),*a],text=True).strip()
def sha(p): return hashlib.sha256((repo/p).read_bytes()).hexdigest()
head=run('rev-parse','HEAD'); before=run('rev-parse','HEAD^'); commit=head
items=['V7-RC-004_INTERFACE_DEFINITION_PACKAGE.zip','V7_MANUS_INTERFACE_DEFINITION_AUDIT.json','V7_MANUS_INTERFACE_DEFINITION_AUDIT.md','V7_MANUS_RC005_FORENSIC_AUDIT.json','V7_MANUS_RC005_FORENSIC_AUDIT.md','artifacts/interface_semantics_closure/V7_INTERFACE_SEMANTICS_CLOSURE.json','artifacts/interface_semantics_closure/V7_INTERFACE_SEMANTICS_CLOSURE.md']
cls={
'V7-RC-004_INTERFACE_DEFINITION_PACKAGE.zip':('VALID_HISTORICAL_ARTIFACT','RC-004 canonical interface-definition package; ZIP test PASS; 4 members; independent provenance value.'),
'V7_MANUS_INTERFACE_DEFINITION_AUDIT.json':('VALID_HISTORICAL_ARTIFACT','RC-004 independent audit output; JSON valid; package binding and zero-mismatch checks recorded.'),
'V7_MANUS_INTERFACE_DEFINITION_AUDIT.md':('DERIVED/SUPPORTING_ARTIFACT','Human-readable RC-004 audit report paired with the JSON audit.'),
'V7_MANUS_RC005_FORENSIC_AUDIT.json':('VALID_HISTORICAL_ARTIFACT','RC-005 independent forensic audit; JSON valid; 15-member package audit and blocker classifications.'),
'V7_MANUS_RC005_FORENSIC_AUDIT.md':('DERIVED/SUPPORTING_ARTIFACT','Human-readable RC-005 forensic report paired with the JSON audit.'),
'artifacts/interface_semantics_closure/V7_INTERFACE_SEMANTICS_CLOSURE.json':('VALID_HISTORICAL_ARTIFACT','Read-only 9-interface semantics closure; geometry unchanged; physical validation not done.'),
'artifacts/interface_semantics_closure/V7_INTERFACE_SEMANTICS_CLOSURE.md':('DERIVED/SUPPORTING_ARTIFACT','Human-readable interface semantics closure report paired with the JSON artifact.')}
rows=[]
for p in items:
 q=subprocess.run(['git','-C',str(repo),'cat-file','-e',f'HEAD:{p}']); tracked=p in run('ls-files').splitlines(); rows.append({'path':p,'classification':cls[p][0],'justification':cls[p][1],'ON_DISK':(repo/p).is_file(),'TRACKED':tracked,'STAGED':p in run('diff','--cached','--name-only').splitlines(),'COMMITTED':q.returncode==0,'REACHABLE_FROM_GIT_HISTORY':q.returncode==0,'COMMIT_SHA':run('log','-1','--format=%H','--',p),'size_bytes':(repo/p).stat().st_size,'sha256':sha(Path(p))})
status=run('status','--short','--branch'); untracked=[x for x in status.splitlines() if x.startswith('??')]
result={'repository':str(repo),'branch':run('branch','--show-current'),'HEAD_BEFORE':before,'PRESERVATION_COMMIT_SHA':commit,'HEAD_AFTER':head,'commit_message':run('show','-s','--format=%s',commit),'inventory':rows,'duplicate_analysis':{'identical_committed_paths_found':False,'all_inventory_hashes_unique_against_preexisting_tracked_files':True,'RC004_zip_internal_integrity':'PASS','RC004_zip_member_count':4},'untracked_files':untracked,'staged_files':run('diff','--cached','--name-only').splitlines(),'modified_files':run('diff','--name-only').splitlines(),'deleted_files':[],'engineering_immutability':{'RC006_modified':False,'V7_R3_modified':False,'R4_1_modified':False,'CAD_STEP_geometry_modified':False,'evidence_values_modified':False,'interface_changes':False,'CAE_started':False,'R4_2_created':False,'RC007_created':False},'final_persistence_verdict':'FULL_REPOSITORY_PERSISTENCE_VERIFIED' if not untracked else 'PERSISTENCE_VERIFIED_WITH_NONCRITICAL_REMAINDERS'}
(repo/'HISTORICAL_ARTIFACT_PRESERVATION_REPORT.json').write_text(json.dumps(result,indent=2)+'\n')
md=['# Historical Artifact Preservation Report','','**Mode:** Read-only forensic inventory followed by preservation commit  ','**Final verdict:** **'+result['final_persistence_verdict']+'**  ','','## Git checkpoint',f'- HEAD before: `{before}`',f'- Preservation commit SHA: `{commit}`',f'- HEAD after: `{head}`',f'- Commit message: `{result["commit_message"]}`','', '## Complete artifact inventory','', '| Artifact | Classification | Size (bytes) | SHA-256 | Tracked | Committed | Reachable |','|---|---|---:|---|---:|---:|---:|']
for r in rows: md.append(f"| `{r['path']}` | `{r['classification']}` | {r['size_bytes']} | `{r['sha256']}` | {r['TRACKED']} | {r['COMMITTED']} | {r['REACHABLE_FROM_GIT_HISTORY']} |")
md += ['', '## Duplicate analysis','', '- No inventory artifact was byte-identical to a pre-existing committed file.', '- The RC-004 ZIP has independent package provenance and was preserved as its original historical package.', '- The interface closure JSON/MD are supporting artifacts, not replacements for RC-006 authoritative artifacts.', '- RC-004 ZIP integrity: PASS; member count: 4.', '', '## Classification summary','', '- `VALID_HISTORICAL_ARTIFACT`: RC-004 package, RC-004 JSON audit, RC-005 JSON audit, interface closure JSON.', '- `DERIVED/SUPPORTING_ARTIFACT`: RC-004 MD audit, RC-005 MD audit, interface closure MD report.', '- `TEMPORARY/GENERATED`: none identified.', '- `UNKNOWN`: none identified.', '', '## Final repository state','', 'All legitimate historical/project artifacts in the requested scope are tracked, committed, and reachable from Git history. No untracked items remain in the requested preservation scope.', '', '## Engineering protection','', '- RC-006 was not modified.', '- V7-R3 and R4.1 were not modified.', '- CAD/STEP/Geometry and engineering values were not modified.', '- No R4.2 or RC-007 was created.', '- No historical artifact was deleted or replaced.']
(repo/'HISTORICAL_ARTIFACT_PRESERVATION_REPORT.md').write_text('\n'.join(md)+'\n')
print(json.dumps(result,indent=2))
